using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderFlow.MVC.Models
{
    public class Role { [Key] public int RoleId { get; set; } [Required, StringLength(50), Index("IX_Roles_Name", IsUnique = true)] public string Name { get; set; } [StringLength(250)] public string Description { get; set; } public virtual ICollection<ApplicationUser> Users { get; set; } = new HashSet<ApplicationUser>(); }
    public class ApplicationUser { [Key] public int UserId { get; set; } [Required, StringLength(100), Index("IX_Users_Email", IsUnique = true)] public string Email { get; set; } [Required, StringLength(120)] public string DisplayName { get; set; } [Required, StringLength(512)] public string PasswordHash { get; set; } [Required, StringLength(128)] public string PasswordSalt { get; set; } public int RoleId { get; set; } public int? CustomerId { get; set; } public bool IsActive { get; set; } = true; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime? LastLoginUtc { get; set; } public virtual Role Role { get; set; } public virtual Customer Customer { get; set; } }
    public class Customer { [Key] public int CustomerId { get; set; } [Required, StringLength(160), Index("IX_Customers_CompanyName")] public string CompanyName { get; set; } [Required, StringLength(120)] public string ContactName { get; set; } [Required, StringLength(120)] public string Email { get; set; } [StringLength(40)] public string Phone { get; set; } [StringLength(250)] public string AddressLine1 { get; set; } [StringLength(120)] public string City { get; set; } [StringLength(80)] public string StateOrRegion { get; set; } [StringLength(20)] public string PostalCode { get; set; } [StringLength(80)] public string Country { get; set; } public CustomerStatus Status { get; set; } = CustomerStatus.Active; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public virtual ICollection<Order> Orders { get; set; } = new HashSet<Order>(); public virtual ICollection<CustomerRequest> Requests { get; set; } = new HashSet<CustomerRequest>(); }
    public class Category { [Key] public int CategoryId { get; set; } [Required, StringLength(100), Index("IX_Categories_Name", IsUnique = true)] public string Name { get; set; } [StringLength(400)] public string Description { get; set; } public bool IsActive { get; set; } = true; public virtual ICollection<Product> Products { get; set; } = new HashSet<Product>(); }
    public class Product { [Key] public int ProductId { get; set; } public int CategoryId { get; set; } [Required, StringLength(50), Index("IX_Products_SKU", IsUnique = true)] public string Sku { get; set; } [Required, StringLength(150), Index("IX_Products_Name")] public string Name { get; set; } [StringLength(1000)] public string Description { get; set; } [Range(0.01, 9999999)] public decimal UnitPrice { get; set; } [Range(0, 999999)] public int ReorderLevel { get; set; } public ProductStatus Status { get; set; } = ProductStatus.Active; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow; public virtual Category Category { get; set; } public virtual Inventory Inventory { get; set; } public virtual ICollection<OrderItem> OrderItems { get; set; } = new HashSet<OrderItem>(); public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new HashSet<InventoryTransaction>(); }
    public class Inventory { [Key] public int InventoryId { get; set; } [Index("IX_Inventory_Product", IsUnique = true)] public int ProductId { get; set; } [Range(0, 999999)] public int QuantityOnHand { get; set; } [Range(0, 999999)] public int ReservedQuantity { get; set; } [NotMapped] public int AvailableQuantity => QuantityOnHand - ReservedQuantity; [Timestamp] public byte[] RowVersion { get; set; } public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow; public virtual Product Product { get; set; } }
    public class InventoryTransaction { [Key] public int InventoryTransactionId { get; set; } public int ProductId { get; set; } public int? OrderId { get; set; } public int? PerformedByUserId { get; set; } public InventoryTransactionType Type { get; set; } public int QuantityDelta { get; set; } public int QuantityBefore { get; set; } public int QuantityAfter { get; set; } [Required, StringLength(500)] public string Notes { get; set; } public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public virtual Product Product { get; set; } public virtual Order Order { get; set; } public virtual ApplicationUser PerformedBy { get; set; } }
    public class Order { [Key] public int OrderId { get; set; } [Required, StringLength(30), Index("IX_Orders_OrderNumber", IsUnique = true)] public string OrderNumber { get; set; } public int CustomerId { get; set; } public int? SalesExecutiveUserId { get; set; } public OrderStatus Status { get; set; } = OrderStatus.Created; [Column(TypeName = "money")] public decimal Subtotal { get; set; } [Column(TypeName = "decimal"), Range(0, 1)] public decimal TaxRate { get; set; } [Column(TypeName = "money")] public decimal TaxAmount { get; set; } [Column(TypeName = "money")] public decimal TotalAmount { get; set; } [StringLength(500)] public string ShippingAddress { get; set; } [StringLength(1000)] public string Notes { get; set; } public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime? ConfirmedAtUtc { get; set; } public DateTime? ShippedAtUtc { get; set; } public DateTime? CompletedAtUtc { get; set; } public virtual Customer Customer { get; set; } [ForeignKey("SalesExecutiveUserId")] public virtual ApplicationUser SalesExecutive { get; set; } public virtual ICollection<OrderItem> Items { get; set; } = new HashSet<OrderItem>(); public virtual ICollection<CustomerRequest> CustomerRequests { get; set; } = new HashSet<CustomerRequest>(); }
    public class OrderItem { [Key] public int OrderItemId { get; set; } public int OrderId { get; set; } public int ProductId { get; set; } [Range(1, 99999)] public int Quantity { get; set; } [Column(TypeName = "money")] public decimal UnitPrice { get; set; } [Column(TypeName = "money")] public decimal LineSubtotal { get; set; } [Column(TypeName = "money")] public decimal TaxAmount { get; set; } [Column(TypeName = "money")] public decimal LineTotal { get; set; } public virtual Order Order { get; set; } public virtual Product Product { get; set; } }
    public class CustomerRequest { [Key] public int CustomerRequestId { get; set; } [Required, StringLength(30), Index("IX_CustomerRequests_RequestNumber", IsUnique = true)] public string RequestNumber { get; set; } public int CustomerId { get; set; } public int? OrderId { get; set; } public int? AssignedEmployeeUserId { get; set; } public RequestType Type { get; set; } public RequestPriority Priority { get; set; } public RequestStatus Status { get; set; } = RequestStatus.Open; [Required, StringLength(1600)] public string Description { get; set; } [StringLength(1600)] public string Resolution { get; set; } public DateTime SubmittedAtUtc { get; set; } = DateTime.UtcNow; public DateTime? ResolvedAtUtc { get; set; } public virtual Customer Customer { get; set; } public virtual Order Order { get; set; } [ForeignKey("AssignedEmployeeUserId")] public virtual ApplicationUser AssignedEmployee { get; set; } public virtual ICollection<RequestHistory> History { get; set; } = new HashSet<RequestHistory>(); }
    public class RequestHistory { [Key] public int RequestHistoryId { get; set; } public int CustomerRequestId { get; set; } public int? AuthorUserId { get; set; } public RequestStatus? PreviousStatus { get; set; } public RequestStatus? NewStatus { get; set; } [Required, StringLength(1600)] public string Message { get; set; } public bool IsVisibleToCustomer { get; set; } = true; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public virtual CustomerRequest CustomerRequest { get; set; } public virtual ApplicationUser Author { get; set; } }
    public class AuditEvent { [Key] public long AuditEventId { get; set; } public int? UserId { get; set; } [Required, StringLength(80), Index("IX_AuditEvents_Entity", 1)] public string EntityType { get; set; } [Required, StringLength(80), Index("IX_AuditEvents_Entity", 2)] public string EntityId { get; set; } public AuditAction Action { get; set; } [StringLength(4000)] public string Detail { get; set; } public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public virtual ApplicationUser User { get; set; } }
}
