/** Operations Ledger: ink-blue structure, warm working surfaces, ledger rules, controlled density, and Cobalt only for intentional operational signals. */
import { useMemo, useState } from "react";
import { Archive, Bell, Boxes, ChevronLeft, ChevronRight, CircleHelp, ClipboardList, Factory, FilePlus2, LayoutDashboard, Menu, MoreHorizontal, PackageCheck, Plus, Search, Send, SlidersHorizontal, Truck, Users, X } from "lucide-react";
import { toast } from "sonner";

const ASSETS = {
  logo: "/manus-storage/orderflow-logo_82786c65.png",
  command: "/manus-storage/orderflow-command-visual_e4a81d43.jpg",
  stock: "/manus-storage/orderflow-stock-signal_db30e7f0.jpg",
  flow: "/manus-storage/orderflow-flow-art_354a845d.jpg",
};

const sections = ["Overview", "Orders", "Inventory", "Products", "Customers", "Requests"] as const;
type Section = (typeof sections)[number];
type OrderStatus = "Created" | "Confirmed" | "Processing" | "Shipped" | "Delivered" | "Completed";
type OrderRecord = { id: string; customer: string; items: number; total: number; status: OrderStatus; placed: string; owner: string };
type ProductRecord = { id: number; sku: string; name: string; category: string; price: number; onHand: number; reserved: number; reorder: number; status: "Active" | "Inactive" };

const navigation: { label: Section; icon: typeof LayoutDashboard; count?: string }[] = [
  { label: "Overview", icon: LayoutDashboard }, { label: "Orders", icon: ClipboardList, count: "24" }, { label: "Inventory", icon: Boxes, count: "3" }, { label: "Products", icon: Archive }, { label: "Customers", icon: Users }, { label: "Requests", icon: CircleHelp, count: "6" },
];
const initialOrders: OrderRecord[] = [
  { id: "OF-20260817-A2F31C", customer: "Northstar Logistics", items: 4, total: 4820, status: "Processing", placed: "Today, 09:42", owner: "Jordan Lee" },
  { id: "OF-20260816-C7D944", customer: "Acme Health Systems", items: 2, total: 1598, status: "Confirmed", placed: "Yesterday, 15:28", owner: "Jordan Lee" },
  { id: "OF-20260816-F6A101", customer: "Helios Analytics", items: 7, total: 3344, status: "Shipped", placed: "Yesterday, 10:11", owner: "R. Walker" },
  { id: "OF-20260815-B4E2AA", customer: "Palmer & Co.", items: 1, total: 1249, status: "Delivered", placed: "15 Aug, 16:04", owner: "Jordan Lee" },
  { id: "OF-20260815-E21F08", customer: "Cedarworks Group", items: 3, total: 987, status: "Completed", placed: "15 Aug, 11:56", owner: "R. Walker" },
  { id: "OF-20260814-A07C1D", customer: "Tidewell Partners", items: 5, total: 2410, status: "Created", placed: "14 Aug, 13:22", owner: "Jordan Lee" },
];
const products: ProductRecord[] = [
  { id: 1, sku: "NET-SW-24P", name: "24-Port Managed Switch", category: "Network Equipment", price: 1249, onHand: 8, reserved: 2, reorder: 12, status: "Active" },
  { id: 2, sku: "NET-AP-6E", name: "Wi-Fi 6E Access Point", category: "Network Equipment", price: 399, onHand: 58, reserved: 4, reorder: 20, status: "Active" },
  { id: 3, sku: "OFF-DK-USB", name: "USB-C Docking Station", category: "Office Systems", price: 219, onHand: 146, reserved: 12, reorder: 30, status: "Active" },
  { id: 4, sku: "WH-THM-4X6", name: "Thermal Shipping Labels 4x6", category: "Warehouse Supplies", price: 42, onHand: 38, reserved: 0, reorder: 60, status: "Active" },
  { id: 5, sku: "WH-PK-VOID", name: "Void Fill Carton Pack", category: "Warehouse Supplies", price: 67, onHand: 71, reserved: 18, reorder: 45, status: "Active" },
];
const customers = [
  { name: "Northstar Logistics", contact: "Ava Martinez", email: "ava@northstar.example", status: "Active", orders: 16, spend: 42680 },
  { name: "Acme Health Systems", contact: "Priya Shah", email: "priya@acmehealth.example", status: "Active", orders: 12, spend: 38910 },
  { name: "Helios Analytics", contact: "Nina Browne", email: "nina@helios.example", status: "Active", orders: 8, spend: 22430 },
  { name: "Palmer & Co.", contact: "Marcus Palmer", email: "marcus@palmer.example", status: "Active", orders: 5, spend: 14850 },
];
const requests = [
  { id: "CR-20260817-920A", title: "Update delivery window", customer: "Northstar Logistics", order: "OF-20260817-A2F31C", priority: "High", status: "Open", text: "Customer requests delivery on Wednesday morning rather than Tuesday afternoon." },
  { id: "CR-20260816-0C12", title: "Add two access points", customer: "Acme Health Systems", order: "OF-20260816-C7D944", priority: "Medium", status: "In progress", text: "Sales is confirming inventory before an order-line amendment is released." },
  { id: "CR-20260815-EE76", title: "Proof of delivery copy", customer: "Helios Analytics", order: "OF-20260816-F6A101", priority: "Low", status: "Resolved", text: "Logistics shared the signed delivery record through the customer portal." },
];
const revenue = [{ m: "Mar", value: 22800 }, { m: "Apr", value: 27600 }, { m: "May", value: 24500 }, { m: "Jun", value: 32400 }, { m: "Jul", value: 30900 }, { m: "Aug", value: 41820 }];
const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const statusClass = (status: string) => status.toLowerCase().replaceAll(" ", "-");

function Status({ value }: { value: string }) { return <span className={`of-status ${statusClass(value)}`}>{value}</span>; }
function PageHead({ kicker, title, subtitle, action }: { kicker: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="of-page-head of-animate"><div><div className="of-kicker">{kicker}</div><h1 className="of-page-title">{title}</h1><p className="of-page-subtitle">{subtitle}</p></div>{action}</div>; }
function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone: string }) { return <article className="of-metric" style={{ "--metric": tone } as React.CSSProperties}><div className="of-metric-label">{label}</div><div className="of-metric-value">{value}</div><div className={`of-metric-note ${note.startsWith("+") ? "up" : ""}`}>{note}</div></article>; }

function Overview({ orders, setActive, openOrder }: { orders: OrderRecord[]; setActive: (section: Section) => void; openOrder: () => void }) {
  const low = products.filter((p) => p.onHand - p.reserved <= p.reorder);
  return <>
    <PageHead kicker="Operations / 17 Aug 2026" title="Keep every order moving." subtitle="Your operational ledger is current through 10:30 AM." action={<button className="of-button" onClick={openOrder}><Plus size={16} /> Create order</button>} />
    <section className="of-metric-grid of-animate of-delay-1"><Metric label="Active customers" value="248" note="+12 this quarter" tone="#2563eb" /><Metric label="Open orders" value="24" note="8 require attention" tone="#dc9e32" /><Metric label="Completed orders" value="186" note="+9.4% vs. July" tone="#2e8a73" /><Metric label="Low-stock products" value="03" note="Reorder action needed" tone="#c3413e" /><Metric label="August revenue" value="$41.8k" note="+16.7% vs. July" tone="#2563eb" /></section>
    <section className="of-overview-grid"><article className="of-card of-animate of-delay-2"><div className="of-card-head"><div><h2>Revenue rhythm</h2><p>Completed and delivered orders over six months.</p></div><div className="of-card-value">$179.0K YTD</div></div><div className="of-chart"><div className="of-ledger-chart"><div className="of-ledger-scale"><span>$45k</span><span>$30k</span><span>$15k</span><span>$0</span></div><div className="of-ledger-plot"><svg viewBox="0 0 600 148" preserveAspectRatio="none" role="img" aria-label="Revenue rose from $22.8k in March to $41.8k in August"><defs><linearGradient id="ofRevenue" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity=".23"/><stop offset="100%" stopColor="#2563eb" stopOpacity="0"/></linearGradient></defs><path d="M20 92 L130 77 L240 86 L350 50 L460 58 L570 18 L570 138 L20 138 Z" fill="url(#ofRevenue)"/><path d="M20 92 L130 77 L240 86 L350 50 L460 58 L570 18" fill="none" stroke="#2563eb" strokeWidth="3"/><g fill="#2563eb" stroke="#fffefa" strokeWidth="3">{[[20,92],[130,77],[240,86],[350,50],[460,58],[570,18]].map(([x,y]) => <circle key={x} cx={x} cy={y} r="4"/>)}</g></svg><div className="of-ledger-labels">{revenue.map((point) => <span key={point.m}>{point.m}<b>{currency(point.value)}</b></span>)}</div></div></div></div></article>
      <aside className="of-animate of-delay-3"><article className="of-card"><div className="of-card-head"><div><h2>Stock watch</h2><p>Products at or below threshold.</p></div><button className="of-button ghost compact" onClick={() => setActive("Inventory")}>View all</button></div><div className="of-stock-list">{low.map((p) => <div className="of-stock-row" key={p.id}><div><p className="of-stock-name">{p.name}</p><div className="of-sku">{p.sku}</div></div><div className="of-stock-qty">{p.onHand - p.reserved} available<span>Reorder at {p.reorder}</span></div></div>)}</div></article><article className="of-visual-card"><img src={ASSETS.command} alt="Distribution center operations"/><div className="of-visual-overlay"><div className="of-kicker" style={{color:"#a7c3ff"}}>Dispatch monitor / HUB-02</div><h3>91% fulfilment pace</h3><p>Orders are moving through the current dispatch window.</p><div className="of-visual-monitor">7 DOCKS ACTIVE · NO EXCEPTIONS</div></div></article></aside>
    </section>
    <section className="of-card of-wide-card of-animate of-delay-3"><div className="of-card-head"><div><h2>Recent order activity</h2><p>New work, owner assignment, and workflow status in one view.</p></div><button className="of-button ghost compact" onClick={() => setActive("Orders")}>Open order ledger <ChevronRight size={13}/></button></div><OrderTable orders={orders.slice(0, 5)} compact onAdvance={() => toast.success("Workflow status updated in the live prototype.")}/></section>
  </>;
}
function OrderTable({ orders, compact = false, onAdvance }: { orders: OrderRecord[]; compact?: boolean; onAdvance: (id: string) => void }) { return <div className="of-table-wrap"><table className="of-table"><thead><tr><th>Order</th><th>Customer</th><th>Value</th><th>Status</th><th>Placed</th>{!compact && <th>Owner</th>}<th aria-label="Actions"/></tr></thead><tbody>{orders.length ? orders.map((o) => <tr key={o.id}><td className="cell-primary cell-mono">{o.id}</td><td><div className="cell-primary">{o.customer}</div><div className="of-sku">{o.items} product line{o.items > 1 ? "s" : ""}</div></td><td className="cell-mono">{currency(o.total)}</td><td><Status value={o.status}/></td><td>{o.placed}</td>{!compact && <td>{o.owner}</td>}<td><button className="of-icon-button" onClick={() => onAdvance(o.id)} aria-label={`Advance ${o.id}`}><MoreHorizontal size={16}/></button></td></tr>) : <tr><td colSpan={compact ? 6 : 7} className="of-empty">No orders match this ledger view.</td></tr>}</tbody></table></div>; }

function OrdersWorkspace({ orders, setOrders, openOrder }: { orders: OrderRecord[]; setOrders: (rows: OrderRecord[]) => void; openOrder: () => void }) {
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All");
  const view = orders.filter((o) => (filter === "All" || o.status === filter) && (o.id.toLowerCase().includes(search.toLowerCase()) || o.customer.toLowerCase().includes(search.toLowerCase())));
  const advance = (id: string) => { const flow: OrderStatus[] = ["Created", "Confirmed", "Processing", "Shipped", "Delivered", "Completed"]; setOrders(orders.map((o) => o.id === id ? { ...o, status: flow[Math.min(flow.indexOf(o.status) + 1, flow.length - 1)] } : o)); toast.success("Order advanced to the next permitted status."); };
  return <><PageHead kicker="Order management" title="Order ledger" subtitle="Search, validate, and move orders through a controlled fulfilment workflow." action={<button className="of-button" onClick={openOrder}><FilePlus2 size={16}/> Create order</button>}/><section className="of-card of-animate of-delay-1"><div className="of-card-head"><div><h2>All orders</h2><p>{orders.length} orders in the operational ledger.</p></div><div className="of-card-value">Created → Completed</div></div><div style={{padding:"16px 20px 5px"}}><div className="of-toolbar"><div className="of-input-wrap"><Search/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search order number or customer"/></div><select className="of-filter" value={filter} onChange={(e) => setFilter(e.target.value)}><option>All</option>{["Created", "Confirmed", "Processing", "Shipped", "Delivered", "Completed"].map(s => <option key={s}>{s}</option>)}</select><button className="of-button ghost compact" onClick={() => toast.info("Export is represented in the ASP.NET MVC implementation notes.")}><SlidersHorizontal size={14}/> Filters</button></div></div><OrderTable orders={view} onAdvance={advance}/><div className="of-pagination"><span>Showing {view.length} of {orders.length} orders</span><span><button>Previous</button> &nbsp; 1 &nbsp; <button>Next</button></span></div></section></>;
}

function InventoryWorkspace({ inventory, setInventory }: { inventory: ProductRecord[]; setInventory: (items: ProductRecord[]) => void }) {
  const [search, setSearch] = useState(""); const [lowOnly, setLowOnly] = useState(false); const rows = inventory.filter(p => p.name.toLowerCase().includes(search.toLowerCase()) || p.sku.toLowerCase().includes(search.toLowerCase())).filter(p => !lowOnly || p.onHand - p.reserved <= p.reorder);
  const adjust = (p: ProductRecord, delta: number) => { setInventory(inventory.map(item => item.id === p.id ? {...item, onHand: Math.max(0, item.onHand + delta)} : item)); toast.success(`${p.sku}: ${delta > 0 ? "+" : ""}${delta} units posted to inventory history.`); };
  return <><PageHead kicker="Inventory management" title="Stock that tells you what to do." subtitle="Available stock reflects on-hand quantity less active order reservations." action={<button className="of-button" onClick={() => toast.info("Choose a stock line to post an adjustment.")}><Plus size={16}/> Stock adjustment</button>}/><div className="of-workspace-grid of-animate of-delay-1"><section className="of-card"><div className="of-card-head"><div><h2>Availability ledger</h2><p>Five active SKUs across three categories.</p></div><div className="of-card-value">Live balance</div></div><div style={{padding:"16px 20px 5px"}}><div className="of-toolbar"><div className="of-input-wrap"><Search/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search SKU or product"/></div><button className={`of-button ghost compact ${lowOnly ? "selected" : ""}`} onClick={() => setLowOnly(!lowOnly)}><Bell size={14}/> {lowOnly ? "Showing low stock" : "Low stock only"}</button></div></div><div className="of-table-wrap"><table className="of-table"><thead><tr><th>Product</th><th>Available</th><th>Reserved</th><th>Threshold</th><th/></tr></thead><tbody>{rows.map(p => { const available = p.onHand - p.reserved; const isLow = available <= p.reorder; return <tr key={p.id}><td><div className="cell-primary">{p.name}</div><div className="of-sku">{p.sku} · {p.category}</div></td><td className="cell-mono" style={{color:isLow ? "#c3413e" : "#213650"}}>{available}</td><td className="cell-mono">{p.reserved}</td><td className="cell-mono">{p.reorder}</td><td><button className="of-button ghost compact" onClick={() => adjust(p, isLow ? p.reorder + 4 - available : 10)}>{isLow ? "Replenish" : "Adjust"}</button></td></tr> })}</tbody></table></div></section><aside className="of-card"><div className="of-inventory-rail"><img src={ASSETS.stock} alt="Organized warehouse stock" style={{width:"100%",height:146,objectFit:"cover",marginBottom:16}}/><div className="of-callout"><strong>3 replenishment signals.</strong><br/>Two products are below their preferred working stock; thermal labels are already below their reorder point.</div><div className="of-mini-section"><h3>Inventory controls</h3><p>Every adjustment creates an immutable transaction with its actor, quantity before and after, reason, and optional order reference.</p></div><div className="of-mini-section"><h3>Availability rule</h3><p>New orders can reserve only the available balance. The reservation is converted to a stock-out when the order enters Shipped.</p></div></div></aside></div></>;
}

function ProductsWorkspace() { const [search, setSearch] = useState(""); const list = products.filter(p => p.name.toLowerCase().includes(search.toLowerCase()) || p.sku.toLowerCase().includes(search.toLowerCase())); return <><PageHead kicker="Product management" title="Product catalogue" subtitle="Commercial master data and inventory thresholds for every sellable SKU." action={<button className="of-button" onClick={() => toast.success("The MVC Product Create view captures SKU, category, pricing, status, and reorder level.")}><Plus size={16}/> New product</button>}/><section className="of-card of-animate of-delay-1"><div className="of-card-head"><div><h2>Active product set</h2><p>Products are categorized, priced, and connected to one inventory record.</p></div><div className="of-card-value">{list.length} products</div></div><div style={{padding:"16px 20px 5px"}}><div className="of-toolbar"><div className="of-input-wrap"><Search/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search product, SKU, or category"/></div><select className="of-filter"><option>All categories</option><option>Network Equipment</option><option>Office Systems</option><option>Warehouse Supplies</option></select></div></div><div className="of-table-wrap"><table className="of-table"><thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>Unit price</th><th>Status</th><th/></tr></thead><tbody>{list.map(p=><tr key={p.id}><td className="cell-mono cell-primary">{p.sku}</td><td className="cell-primary">{p.name}</td><td>{p.category}</td><td className="cell-mono">{currency(p.price)}</td><td><Status value={p.status}/></td><td><button className="of-icon-button" onClick={() => toast.info(`${p.sku} is ready for edit in the MVC module.`)}><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div></section></> }
function CustomersWorkspace() { const [search, setSearch] = useState(""); const list = customers.filter(c => c.name.toLowerCase().includes(search.toLowerCase()) || c.contact.toLowerCase().includes(search.toLowerCase())); return <><PageHead kicker="Customer management" title="Customer relationships" subtitle="Profiles, contacts, activity and order history presented as an accountable record." action={<button className="of-button" onClick={() => toast.success("The MVC Customer Create view is available to Admin and Sales Executive roles.")}><Plus size={16}/> Add customer</button>}/><section className="of-card of-animate of-delay-1"><div className="of-card-head"><div><h2>Customer directory</h2><p>Active accounts sorted by company name.</p></div><div className="of-card-value">248 active</div></div><div style={{padding:"16px 20px 5px"}}><div className="of-toolbar"><div className="of-input-wrap"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company or contact"/></div><select className="of-filter"><option>Active customers</option><option>Inactive customers</option></select></div></div><div className="of-table-wrap"><table className="of-table"><thead><tr><th>Company</th><th>Primary contact</th><th>Order history</th><th>Lifetime value</th><th>Status</th><th/></tr></thead><tbody>{list.map(c=><tr key={c.name}><td className="cell-primary">{c.name}</td><td><div>{c.contact}</div><div className="of-sku">{c.email}</div></td><td className="cell-mono">{c.orders} orders</td><td className="cell-mono">{currency(c.spend)}</td><td><Status value={c.status}/></td><td><button className="of-icon-button" onClick={()=>toast.info(`${c.name} profile selected.`)}><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div></section></> }
function RequestsWorkspace() { const [filter, setFilter] = useState("All"); const list = requests.filter(r => filter === "All" || r.status === filter); return <><PageHead kicker="Customer requests" title="Requests that stay accountable." subtitle="Change requests, delivery questions and resolutions remain connected to the originating order." action={<button className="of-button" onClick={() => toast.success("The customer portal request form is represented in the MVC module.")}><Plus size={16}/> Log request</button>}/><div className="of-workspace-grid of-animate of-delay-1"><section className="of-card"><div className="of-card-head"><div><h2>Service queue</h2><p>{list.length} customer-facing requests in view.</p></div><select className="of-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Open</option><option>In progress</option><option>Resolved</option></select></div>{list.map(r=><article className="of-request-card" key={r.id}><div className="of-request-top"><div><div className="of-sku">{r.id} · {r.order}</div><h3 className="of-request-title">{r.title}</h3><p>{r.text}</p></div><Status value={r.priority === "High" ? "Urgent" : r.status}/></div><div className="of-request-meta"><span>{r.customer}</span><span>Assigned: Jordan Lee</span><button onClick={() => toast.success(`${r.id} marked as in progress.`)}>Update status</button></div></article>)}</section><aside className="of-card"><div className="of-inventory-rail"><div className="of-mini-section"><h3>Communication history</h3><p>Every update records the prior and next request status, author, timestamp, message and customer visibility setting.</p></div><div className="of-mini-section"><h3>Priority routing</h3><p>Urgent requests surface first. Admins, sales executives and inventory managers can assign an owner and resolution.</p></div><div className="of-mini-section"><h3>Customer visibility</h3><p>Internal notes remain protected while approved updates become part of the customer’s communication trail.</p></div></div></aside></div></> }

function OrderDrawer({ close, addOrder, inventory }: { close: () => void; addOrder: (order: OrderRecord) => void; inventory: ProductRecord[] }) {
  const [customer, setCustomer] = useState("Northstar Logistics"); const [productId, setProductId] = useState(2); const [qty, setQty] = useState(2); const [tax, setTax] = useState(8); const product = inventory.find(p => p.id === productId)!; const available = product.onHand - product.reserved; const subtotal = product.price * qty; const taxValue = subtotal * tax / 100; const valid = qty > 0 && qty <= available;
  const submit = () => { if (!valid) { toast.error("Quantity exceeds available inventory. Adjust the line before saving."); return; } const id = `OF-20260817-${Math.random().toString(16).slice(2,8).toUpperCase()}`; addOrder({id, customer, items: 1, total: subtotal + taxValue, status:"Created", placed:"Just now", owner:"Jordan Lee"}); toast.success(`${id} created; ${qty} units reserved for fulfilment.`); close(); };
  return <><div className="of-drawer-shade" onClick={close}/><aside className="of-drawer" aria-label="Create a new order"><div className="of-drawer-head"><div><div className="of-kicker">Sales order</div><h2>Build a controlled order.</h2></div><button className="of-icon-button" onClick={close}><X size={17}/></button></div><div className="of-drawer-body"><div className="of-field"><label>Customer</label><select value={customer} onChange={e=>setCustomer(e.target.value)}>{customers.map(c=><option key={c.name}>{c.name}</option>)}</select></div><div className="of-field"><label>Product line</label><div className="of-order-line"><select value={productId} onChange={e=>setProductId(Number(e.target.value))}>{inventory.map(p=><option value={p.id} key={p.id}>{p.sku} · {p.name}</option>)}</select><input type="number" min="1" max={available} value={qty} onChange={e=>setQty(Number(e.target.value))}/><button className="of-line-remove" onClick={()=>toast.info("Multiple lines are supported by the MVC order ViewModel.")} title="Remove line"><X size={15}/></button></div></div><div className={`of-availability ${!valid || available <= product.reorder ? "low" : ""}`}>{valid ? `${available} units available for reservation.` : `Only ${available} units can be reserved.`} {available <= product.reorder && valid ? " This product is at its reorder threshold." : ""}</div><div className="of-field"><label>Tax rate</label><select value={tax} onChange={e=>setTax(Number(e.target.value))}><option value={0}>0%</option><option value={5}>5%</option><option value={8}>8%</option><option value={10}>10%</option></select></div><div className="of-field"><label>Shipping instructions</label><textarea placeholder="Add address or fulfilment notes"/></div><div className="of-calculation"><div className="of-calc-row"><span>Subtotal</span><span>{currency(subtotal)}</span></div><div className="of-calc-row"><span>Tax ({tax}%)</span><span>{currency(taxValue)}</span></div><div className="of-calc-row total"><span>Order total</span><span>{currency(subtotal + taxValue)}</span></div></div></div><div className="of-drawer-foot"><button className="of-button ghost" onClick={close}>Cancel</button><button className="of-button" onClick={submit}><Send size={15}/> Create & reserve</button></div></aside></>;
}

export default function OrderFlowApp() {
  const [active, setActive] = useState<Section>("Overview"); const [mobileOpen, setMobileOpen] = useState(false); const [drawer, setDrawer] = useState(false); const [orders, setOrders] = useState(initialOrders); const [inventory, setInventory] = useState(products); const [search, setSearch] = useState("");
  const activeTitle = active === "Overview" ? "Operations ledger" : active; const createOrder = () => setDrawer(true);
  const content = useMemo(() => { if (active === "Overview") return <Overview orders={orders} setActive={setActive} openOrder={createOrder}/>; if (active === "Orders") return <OrdersWorkspace orders={orders} setOrders={setOrders} openOrder={createOrder}/>; if (active === "Inventory") return <InventoryWorkspace inventory={inventory} setInventory={setInventory}/>; if (active === "Products") return <ProductsWorkspace/>; if (active === "Customers") return <CustomersWorkspace/>; return <RequestsWorkspace/>; }, [active, orders, inventory]);
  return <div className="of-shell"><aside className={`of-sidebar ${mobileOpen ? "open" : ""}`}><a className="of-brand" href="#overview" onClick={(e)=>{e.preventDefault();setActive("Overview");setMobileOpen(false)}}><img className="of-brand-mark" src={ASSETS.logo} alt="OrderFlow"/><span className="of-brand-text">order<span>flow</span></span></a><div className="of-nav-label">Workspace</div><nav className="of-nav">{navigation.map(({label, icon: Icon, count})=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setMobileOpen(false)}}><Icon size={17}/><span>{label}</span>{count&&<span className="nav-count">{count}</span>}</button>)}</nav><div className="of-sidebar-foot"><div className="of-help"><CircleHelp size={17}/><span>Need a hand?<br/>Open the operations guide.</span></div></div></aside><main className="of-main"><header className="of-topbar"><button className="of-mobile-toggle" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Toggle navigation"><Menu size={18}/></button><div className="of-breadcrumb"><img src={ASSETS.logo} alt=""/> <span>OrderFlow / <strong>{activeTitle}</strong></span></div><div className="of-global-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records" onKeyDown={e=>{if(e.key==="Enter"){setActive("Orders");toast.info(`Order ledger opened for “${search}”.`)}}}/></div><button className="of-icon-button" onClick={()=>toast.info("No new operational notifications.")}><Bell size={16}/></button><div className="of-user"><div className="of-avatar">JL</div><div className="of-user-copy"><strong>Jordan Lee</strong>Sales Executive</div></div></header><div className="of-content">{content}</div></main>{drawer&&<OrderDrawer close={()=>setDrawer(false)} addOrder={(order)=>setOrders([order,...orders])} inventory={inventory}/>}</div>;
}
