/* Operations Ledger MVC interactions: immediate validation and explicit AJAX confirmation. */
(function ($) {
  "use strict";
  function token() { return $("input[name='__RequestVerificationToken']").first().val(); }
  function showMessage(text, error) { var box = $("#of-ajax-message"); if (!box.length) { box = $("<div id='of-ajax-message' class='alert of-mvc-alert mt-3'></div>").prependTo(".of-mvc-content"); } box.removeClass("alert-success alert-danger").addClass(error ? "alert-danger" : "alert-success").text(text).show(); }
  $(document).on("click", "[data-order-status]", function () { var button = $(this); $.ajax({ url: "/Orders/UpdateStatus", type: "POST", data: { __RequestVerificationToken: token(), OrderId: button.data("order-id"), Status: button.data("order-status") } }).done(function (r) { showMessage(r.message); window.setTimeout(function(){ window.location.reload(); }, 450); }).fail(function (xhr) { showMessage(xhr.responseText || "The status transition could not be completed.", true); }); });
  $(document).on("click", "[data-adjust-inventory]", function () { var button = $(this); var delta = window.prompt("Quantity adjustment (+/-):", "0"); if (delta === null) return; $.ajax({ url: "/Inventory/Adjust", type: "POST", data: { __RequestVerificationToken: token(), ProductId: button.data("product-id"), QuantityDelta: delta, Type: Number(delta) >= 0 ? 3 : 4, Notes: "Adjustment posted from inventory ledger." } }).done(function(r) { showMessage(r.message); window.setTimeout(function(){ window.location.reload(); },450); }).fail(function(xhr) { showMessage(xhr.responseText || "The adjustment was rejected.", true); }); });
  $(document).on("change", ".of-order-product, .of-order-quantity, #TaxRate", function () { var product = $(".of-order-product").val(), quantity = $(".of-order-quantity").val(); if (!product || !quantity) return; $.getJSON("/Orders/CheckAvailability", { productId: product, quantity: quantity }, function (r) { $("#of-availability").text(r.ok ? r.available + " units available for reservation." : "Only " + r.available + " units available.").toggleClass("text-danger", !r.ok); }); });
}(jQuery));
